[[aws_c_http]]
arch = "aarch64"
git-tree-sha1 = "07de706dd566cb4eb9c96744696afbfdf138d88f"
os = "macos"

    [[aws_c_http.download]]
    sha256 = "6bf059ffba337f459ddfc844957cbf1635c7687bf5cc0acfdffd0a3d7c8f9f74"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_http_jll.jl/releases/download/aws_c_http-v0.11.1+0/aws_c_http.v0.11.1.aarch64-apple-darwin.tar.gz"
[[aws_c_http]]
arch = "aarch64"
git-tree-sha1 = "dec2f155ca8453d1e69b3dfbfaf8279a46788b4b"
libc = "glibc"
os = "linux"

    [[aws_c_http.download]]
    sha256 = "82df3c1f63befb16a6b772f843902e203a9eb1c13bd88146aad68255931947e8"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_http_jll.jl/releases/download/aws_c_http-v0.11.1+0/aws_c_http.v0.11.1.aarch64-linux-gnu.tar.gz"
[[aws_c_http]]
arch = "aarch64"
git-tree-sha1 = "79da97ab3bf56789e74be9753da064a8300ff306"
libc = "musl"
os = "linux"

    [[aws_c_http.download]]
    sha256 = "6a35af96deb2bd867c1113e8bdcfc0fff7344f3304c070f03910c742a8ed7035"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_http_jll.jl/releases/download/aws_c_http-v0.11.1+0/aws_c_http.v0.11.1.aarch64-linux-musl.tar.gz"
[[aws_c_http]]
arch = "aarch64"
git-tree-sha1 = "ebd6bac25899a1f29663ca85251290aaae1f31fb"
os = "freebsd"

    [[aws_c_http.download]]
    sha256 = "0c0daa458b8d0c3ef09a5f55ce322b4faad00b0532187f8d820c2be86bf80f13"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_http_jll.jl/releases/download/aws_c_http-v0.11.1+0/aws_c_http.v0.11.1.aarch64-unknown-freebsd.tar.gz"
[[aws_c_http]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "4052c302b687d648703453c5a15dba1045c6249d"
libc = "glibc"
os = "linux"

    [[aws_c_http.download]]
    sha256 = "d74f86c221973ad47efb5e1b5c291c15b01c98ddf073fd0aa8d2ec049a6d0d5f"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_http_jll.jl/releases/download/aws_c_http-v0.11.1+0/aws_c_http.v0.11.1.armv6l-linux-gnueabihf.tar.gz"
[[aws_c_http]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "58b84dacc93eacd30e209230c8939a8b38b8668c"
libc = "musl"
os = "linux"

    [[aws_c_http.download]]
    sha256 = "d4cd73136f3fdf1eb4ae32c2864352f0c81102efb1f21d0b527120903761158a"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_http_jll.jl/releases/download/aws_c_http-v0.11.1+0/aws_c_http.v0.11.1.armv6l-linux-musleabihf.tar.gz"
[[aws_c_http]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "61ed3e4e8a85b34fbe9fe5691f0f7293e65e71fa"
libc = "glibc"
os = "linux"

    [[aws_c_http.download]]
    sha256 = "143668291f54e8ead9a94d55d65ff1149a4af08d6bdaa9b5c873fca9f9b9942d"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_http_jll.jl/releases/download/aws_c_http-v0.11.1+0/aws_c_http.v0.11.1.armv7l-linux-gnueabihf.tar.gz"
[[aws_c_http]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "787e9d78203b3c89114476019ac90b31ded64f4c"
libc = "musl"
os = "linux"

    [[aws_c_http.download]]
    sha256 = "9d30cafe5ed10f41f685c23b134c8a94624be926d800d3332b251b2b2c8bad0e"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_http_jll.jl/releases/download/aws_c_http-v0.11.1+0/aws_c_http.v0.11.1.armv7l-linux-musleabihf.tar.gz"
[[aws_c_http]]
arch = "i686"
git-tree-sha1 = "2965bced9cc522d7b8947b90a08b2460219a69bb"
libc = "glibc"
os = "linux"

    [[aws_c_http.download]]
    sha256 = "863f7e5d10cf97817c689431c46c7bbe5f68d6f92f790b30e490a326b9d2a116"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_http_jll.jl/releases/download/aws_c_http-v0.11.1+0/aws_c_http.v0.11.1.i686-linux-gnu.tar.gz"
[[aws_c_http]]
arch = "i686"
git-tree-sha1 = "4b64ade927785d5dcd5b884055bfe181ed7083e0"
libc = "musl"
os = "linux"

    [[aws_c_http.download]]
    sha256 = "db391b1e3ced087bc7bd3c006e90704c504b370b9899c9e238233f0735a383c4"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_http_jll.jl/releases/download/aws_c_http-v0.11.1+0/aws_c_http.v0.11.1.i686-linux-musl.tar.gz"
[[aws_c_http]]
arch = "powerpc64le"
git-tree-sha1 = "be223908613c8c0504711dae2b175ce17043f32e"
libc = "glibc"
os = "linux"

    [[aws_c_http.download]]
    sha256 = "0e65a01b4282a101f0adf649b1b321cd89c64d1300177e87611ca566f8a0bed4"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_http_jll.jl/releases/download/aws_c_http-v0.11.1+0/aws_c_http.v0.11.1.powerpc64le-linux-gnu.tar.gz"
[[aws_c_http]]
arch = "riscv64"
git-tree-sha1 = "efc42b9a56fd90cb3c85d4e14e9ad35cf4562566"
libc = "glibc"
os = "linux"

    [[aws_c_http.download]]
    sha256 = "0dd5b1d9323a2dbd78319bbb06be4f6e8147a764d786b28956b920173d15a3e7"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_http_jll.jl/releases/download/aws_c_http-v0.11.1+0/aws_c_http.v0.11.1.riscv64-linux-gnu.tar.gz"
[[aws_c_http]]
arch = "x86_64"
git-tree-sha1 = "44e696f0c03daa32c1ac2ad83ca3315785b3c094"
os = "macos"

    [[aws_c_http.download]]
    sha256 = "c82db975ecf9d05a6894ed98fca1991b96bc2d9a1a33c8883eee062065c16340"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_http_jll.jl/releases/download/aws_c_http-v0.11.1+0/aws_c_http.v0.11.1.x86_64-apple-darwin.tar.gz"
[[aws_c_http]]
arch = "x86_64"
git-tree-sha1 = "c68bd4f280ba180003228f9ae6660f2e4b8bbb24"
libc = "glibc"
os = "linux"

    [[aws_c_http.download]]
    sha256 = "a04267b31762ed892ed284a68927d8ecbcd942eac1391c0b5a18e4eb39cfcacb"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_http_jll.jl/releases/download/aws_c_http-v0.11.1+0/aws_c_http.v0.11.1.x86_64-linux-gnu.tar.gz"
[[aws_c_http]]
arch = "x86_64"
git-tree-sha1 = "9deaf57617c0f0586053c16ca3e65181982ba79c"
libc = "musl"
os = "linux"

    [[aws_c_http.download]]
    sha256 = "70b9928207c3e420ebf9f0126232b6b1f4de9a371bdf00791ce402d61b7579cd"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_http_jll.jl/releases/download/aws_c_http-v0.11.1+0/aws_c_http.v0.11.1.x86_64-linux-musl.tar.gz"
[[aws_c_http]]
arch = "x86_64"
git-tree-sha1 = "364d691de282eb71bf5d17f3feae9f80c912ce8b"
os = "freebsd"

    [[aws_c_http.download]]
    sha256 = "6fcd79acdf68c48d6a899334c226f3b871a5997232255a4ba1b89e1aa774a41f"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_http_jll.jl/releases/download/aws_c_http-v0.11.1+0/aws_c_http.v0.11.1.x86_64-unknown-freebsd.tar.gz"
[[aws_c_http]]
arch = "x86_64"
git-tree-sha1 = "c9e22a1f4478bcf885c9f6bdcb54cb8194b0cc46"
os = "windows"

    [[aws_c_http.download]]
    sha256 = "c4385b092f3f0f98dee0b471f75481bf5d0d3219191d28d2ed49e3ee23362bec"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_http_jll.jl/releases/download/aws_c_http-v0.11.1+0/aws_c_http.v0.11.1.x86_64-w64-mingw32.tar.gz"
