[[aws_c_http]]
arch = "aarch64"
git-tree-sha1 = "8e389201bc59197f620961395c559f57f68a329f"
os = "macos"

    [[aws_c_http.download]]
    sha256 = "a0dbaf1f73319ca88254e5f0097fcb5cd8fb88bcb902550b735753398f0c291a"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_http_jll.jl/releases/download/aws_c_http-v0.10.12+0/aws_c_http.v0.10.12.aarch64-apple-darwin.tar.gz"
[[aws_c_http]]
arch = "aarch64"
git-tree-sha1 = "9a9861d19832664f524ad62aeb313ccee342f942"
libc = "glibc"
os = "linux"

    [[aws_c_http.download]]
    sha256 = "81a679d26c437de34b66ff49a89e2a4ab008780aba132bb968a225b4f27af3e1"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_http_jll.jl/releases/download/aws_c_http-v0.10.12+0/aws_c_http.v0.10.12.aarch64-linux-gnu.tar.gz"
[[aws_c_http]]
arch = "aarch64"
git-tree-sha1 = "c19dbf9d0f9dbe9aa6f38289f931188da52dc5e9"
libc = "musl"
os = "linux"

    [[aws_c_http.download]]
    sha256 = "976af5e21dd7e95ab204d58f33b2b26ab794de96b6227c859c888d157b4a807e"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_http_jll.jl/releases/download/aws_c_http-v0.10.12+0/aws_c_http.v0.10.12.aarch64-linux-musl.tar.gz"
[[aws_c_http]]
arch = "aarch64"
git-tree-sha1 = "550c6d4a7d60aa738fde0441ca7fb321d82d1a45"
os = "freebsd"

    [[aws_c_http.download]]
    sha256 = "ac9837fc81cbfa5dc4f43753eeccee147cec1e46db51f0052d7a2f2d1aa8b431"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_http_jll.jl/releases/download/aws_c_http-v0.10.12+0/aws_c_http.v0.10.12.aarch64-unknown-freebsd.tar.gz"
[[aws_c_http]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "4dac49b8b568fc75257f932ea0b2e6329a6a7f06"
libc = "glibc"
os = "linux"

    [[aws_c_http.download]]
    sha256 = "2bfd10274310b050882f30dbc83246c19fb096123ae770ddc951e4fef536a1d2"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_http_jll.jl/releases/download/aws_c_http-v0.10.12+0/aws_c_http.v0.10.12.armv6l-linux-gnueabihf.tar.gz"
[[aws_c_http]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "05813429b738c258749b7be77d401d15df38df4b"
libc = "musl"
os = "linux"

    [[aws_c_http.download]]
    sha256 = "dafbfea8f6ce5cb28123032b9afe47c9f085123d667fc3cc44bcf8dae1056abb"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_http_jll.jl/releases/download/aws_c_http-v0.10.12+0/aws_c_http.v0.10.12.armv6l-linux-musleabihf.tar.gz"
[[aws_c_http]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "62fa927c91df02490d6204525a5e863906f60422"
libc = "glibc"
os = "linux"

    [[aws_c_http.download]]
    sha256 = "38e217fca6275a225162a73c7d98574fdb20350abcd5b58ecdb47e0a4f1e9cd8"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_http_jll.jl/releases/download/aws_c_http-v0.10.12+0/aws_c_http.v0.10.12.armv7l-linux-gnueabihf.tar.gz"
[[aws_c_http]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "d8804fd48a9af132402f6b039d0c3936725a2772"
libc = "musl"
os = "linux"

    [[aws_c_http.download]]
    sha256 = "8609b954e148836d7f9e3374a0aaee0c12c13ca9e105b7e71a7eb0a32fb7160a"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_http_jll.jl/releases/download/aws_c_http-v0.10.12+0/aws_c_http.v0.10.12.armv7l-linux-musleabihf.tar.gz"
[[aws_c_http]]
arch = "i686"
git-tree-sha1 = "3afeebf2d1e98ef9e50fa8155b1e532eb26cd522"
libc = "glibc"
os = "linux"

    [[aws_c_http.download]]
    sha256 = "ef11d88978b4ee57790c8fe636723713989c460e7ed919643c15b853e27a1465"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_http_jll.jl/releases/download/aws_c_http-v0.10.12+0/aws_c_http.v0.10.12.i686-linux-gnu.tar.gz"
[[aws_c_http]]
arch = "i686"
git-tree-sha1 = "c661f4ebff2fcfceaf9a023bdefde04968b1fcbd"
libc = "musl"
os = "linux"

    [[aws_c_http.download]]
    sha256 = "10ed3367c17f3c63c5768a9b4bf99cbfcae1f872e5de9048cc645e29dd0a2d46"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_http_jll.jl/releases/download/aws_c_http-v0.10.12+0/aws_c_http.v0.10.12.i686-linux-musl.tar.gz"
[[aws_c_http]]
arch = "powerpc64le"
git-tree-sha1 = "26a504ff40ea49e8a5ad549f5b7069078b4dcf8b"
libc = "glibc"
os = "linux"

    [[aws_c_http.download]]
    sha256 = "2b249dbe390abd7fc277893e2fb96913612d532deb9815da52d951b3bb53d822"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_http_jll.jl/releases/download/aws_c_http-v0.10.12+0/aws_c_http.v0.10.12.powerpc64le-linux-gnu.tar.gz"
[[aws_c_http]]
arch = "riscv64"
git-tree-sha1 = "e80ece4af86f87317d5e29a94b3f1206a0fc14a4"
libc = "glibc"
os = "linux"

    [[aws_c_http.download]]
    sha256 = "8f65ed37e645a1216f7c1b5b3420798901d2f211072e528396869da9f9a91106"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_http_jll.jl/releases/download/aws_c_http-v0.10.12+0/aws_c_http.v0.10.12.riscv64-linux-gnu.tar.gz"
[[aws_c_http]]
arch = "x86_64"
git-tree-sha1 = "14d05b6cd7db9e196686a8a2ac4126bfcd8f3ce2"
os = "macos"

    [[aws_c_http.download]]
    sha256 = "5014572c3740161cbad5782fc968de40c9cbbcd6a26089ee12609154598b2739"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_http_jll.jl/releases/download/aws_c_http-v0.10.12+0/aws_c_http.v0.10.12.x86_64-apple-darwin.tar.gz"
[[aws_c_http]]
arch = "x86_64"
git-tree-sha1 = "77c954ba4c28cff513f5ec127cfefa2ac5be4d1d"
libc = "glibc"
os = "linux"

    [[aws_c_http.download]]
    sha256 = "77c69be9ae65cc0068668f25c990d3311a87d4dbd38870d6f4ba94ae78fda21a"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_http_jll.jl/releases/download/aws_c_http-v0.10.12+0/aws_c_http.v0.10.12.x86_64-linux-gnu.tar.gz"
[[aws_c_http]]
arch = "x86_64"
git-tree-sha1 = "2445eb583f4315baed4ebe96f53ca3a79f710df6"
libc = "musl"
os = "linux"

    [[aws_c_http.download]]
    sha256 = "783bb68b09dbfa1fc4904c172769d0581d97f5614da3e1da1a6fb7ddfba61078"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_http_jll.jl/releases/download/aws_c_http-v0.10.12+0/aws_c_http.v0.10.12.x86_64-linux-musl.tar.gz"
[[aws_c_http]]
arch = "x86_64"
git-tree-sha1 = "fa21ea77d3b590818479eac6d7430727fd589bfb"
os = "freebsd"

    [[aws_c_http.download]]
    sha256 = "aa6413f382fb6190dd480e723ba25a25ccafb290aa6df9df11189d32d55b25e0"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_http_jll.jl/releases/download/aws_c_http-v0.10.12+0/aws_c_http.v0.10.12.x86_64-unknown-freebsd.tar.gz"
[[aws_c_http]]
arch = "x86_64"
git-tree-sha1 = "b75a59b87b2e3270ba5f95e00079075d94b43c06"
os = "windows"

    [[aws_c_http.download]]
    sha256 = "4e4f720777a896746135f0e6f6da01d5f2fe1afb5f5ae07d2f10f342e2f69b5d"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_http_jll.jl/releases/download/aws_c_http-v0.10.12+0/aws_c_http.v0.10.12.x86_64-w64-mingw32.tar.gz"
